Numpy Array Operations

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a+5

array([ 6,  7,  8,  9, 10])

In [5]:
a-2

array([-1,  0,  1,  2,  3])

In [8]:
a*3

array([ 3,  6,  9, 12, 15])

In [9]:
a/6

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333])

In [11]:
ab = np.array([[1,2],[3,4]])

In [12]:
ac = np.array([[5,6],[7,8]])

In [13]:
ab+ac


array([[ 6,  8],
       [10, 12]])

In [14]:
ab-ac

array([[-4, -4],
       [-4, -4]])

In [15]:
ab*ac


array([[ 5, 12],
       [21, 32]])

In [17]:
ab.dot(ac)    #dot product

array([[19, 22],
       [43, 50]])

In [18]:
a>1

array([False,  True,  True,  True,  True])

In [19]:
np.mean(ab)

2.5

In [20]:
np.median(ab)

2.5

In [21]:
np.sum(ab)

10

In [22]:
np.std(ab)

1.118033988749895

In [24]:
np.square(ab)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

Advance Numpy Operations

In [25]:
df = np.arange(25)

In [26]:
df

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
df[1:5]

array([1, 2, 3, 4])

In [30]:
cf = np.arange(3,5)

In [31]:
cf


array([3, 4])

In [38]:
gf = np.arange(2,6)

In [39]:
gf

array([2, 3, 4, 5])

In [40]:
df[2:5] = -100

In [41]:
df

array([   0,    1, -100, -100, -100,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24])

In [42]:
df.reshape(5,5)

array([[   0,    1, -100, -100, -100],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24]])

In [43]:
df[4:5][5:5] = -200

In [44]:
df

array([   0,    1, -100, -100, -100,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24])

In [45]:
lf = df.reshape(5,5)

In [46]:
lf

array([[   0,    1, -100, -100, -100],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24]])

In [47]:
lf[4:5][5:5] 

array([], shape=(0, 5), dtype=int32)

In [48]:
lf[3:4][4:5] 

array([], shape=(0, 5), dtype=int32)

In [49]:
lf[4:5]

array([[20, 21, 22, 23, 24]])

In [52]:
lf[4:5] = 300.42   # broadcasting

In [53]:
lf

array([[   0,    1, -100, -100, -100],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [ 300,  300,  300,  300,  300]])