LAMBDA FUNCTIONS

In [7]:
addUserBased = lambda x,y,z:x+y+z


In [8]:
addUserBased(5,3,5)

13

1D 2D 3D Numpy Arrays

In [9]:
import numpy as np

In [13]:
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]

one_d   = np.array(x)
two_d   = np.array([x,y])
three_d = np.array([x,y,z])

type(one_d)


numpy.ndarray

In [14]:
type(two_d)


numpy.ndarray

In [15]:
type(three_d)

numpy.ndarray

Eye, zero, one, rand one dimensional matrix

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
one_d

array([1, 2, 3])

In [22]:
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
three_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.random.randn(3)

array([ 0.67345211, -1.87038007, -1.27707344])

In [27]:
np.random.randn(3,4)

array([[-0.26218906, -0.35683486,  0.72417286,  1.1789584 ],
       [-1.96181049,  0.56963552, -0.48319758, -2.92732044],
       [-0.75358637,  0.09819467, -1.37322817, -1.14873126]])

In [28]:
np.random.rand(3,4)

array([[0.76122901, 0.31585575, 0.15067947, 0.18945915],
       [0.7371638 , 0.13541287, 0.00525897, 0.09833865],
       [0.12257261, 0.79537896, 0.25041547, 0.16144589]])

In [29]:
np.random.randint(3,4)

3

In [30]:
np.random.randint(3,6,2)

array([3, 5])

In [32]:
np.random.randint(3,8,2)

array([6, 3])