LAMBDA FUNCTIONS

In [7]:
addUserBased = lambda x,y,z:x+y+z


In [8]:
addUserBased(5,3,5)

13

1D 2D 3D Numpy Arrays

In [9]:
import numpy as np

In [13]:
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]

one_d   = np.array(x)
two_d   = np.array([x,y])
three_d = np.array([x,y,z])

type(one_d)


numpy.ndarray

In [14]:
type(two_d)


numpy.ndarray

In [15]:
type(three_d)

numpy.ndarray

Eye, zero, one, rand one dimensional matrix

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
one_d

array([1, 2, 3])

In [22]:
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
three_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.random.randn(3)

array([ 0.67345211, -1.87038007, -1.27707344])

In [27]:
np.random.randn(3,4)

array([[-0.26218906, -0.35683486,  0.72417286,  1.1789584 ],
       [-1.96181049,  0.56963552, -0.48319758, -2.92732044],
       [-0.75358637,  0.09819467, -1.37322817, -1.14873126]])

In [28]:
np.random.rand(3,4)

array([[0.76122901, 0.31585575, 0.15067947, 0.18945915],
       [0.7371638 , 0.13541287, 0.00525897, 0.09833865],
       [0.12257261, 0.79537896, 0.25041547, 0.16144589]])

In [29]:
np.random.randint(3,4)

3

In [30]:
np.random.randint(3,6,2)

array([3, 5])

In [32]:
np.random.randint(3,8,2)

array([6, 3])

arange,linspace

In [34]:
np.arange(3,12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
np.arange(3,20,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [36]:
np.linspace(2,4) #5 rows and 10 columns default

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [37]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [39]:
np.linspace(2,6,8)

array([2.        , 2.57142857, 3.14285714, 3.71428571, 4.28571429,
       4.85714286, 5.42857143, 6.        ])

In [40]:
one_d.shape

(3,)

In [41]:
two_d.shape

(2, 3)

In [42]:
three_d.shape

(3, 3)

In [44]:
one_d.reshape(1,3)

array([[1, 2, 3]])

In [45]:
two_d.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [46]:
three_d.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [47]:
two_d.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])